In [1]:
from google.colab import files

uploaded = files.upload()

Saving employee_management_dataset.csv to employee_management_dataset.csv

Write an SQL query to display all employee details from the Employee table.

In [2]:
import pandas as pd

df = pd.read_csv("employee_management_dataset.csv")

In [3]:
df

,EmployeeID,FirstName,LastName,Gender,DateOfBirth,Email,PhoneNumber,Department,JobTitle,HireDate,EmploymentType,Location,Salary,ManagerID,Status
0,EMP1001,Mark,Johnson,Male,1977-09-05,mark.johnson@company.com,001-218-519-6001x3389,Engineering,Engineering Manager,2020-04-12,Full-Time,Chennai,74481,EMP1000,Terminated
1,EMP1002,Mike,Miles,Male,1983-01-09,mike.miles@company.com,302-765-4235x116,Customer Support,Support Executive,2022-01-31,Full-Time,Pune,34743,EMP1000,On Leave
2,EMP1003,Ryan,Munoz,Male,1997-05-14,ryan.munoz@company.com,+1-516-318-4959,Human Resources,HR Generalist,2024-04-26,Full-Time,Hyderabad,43902,EMP1000,Active
3,EMP1004,Angel,Perez,Male,1978-03-18,angel.perez@company.com,516.647.5255,Customer Support,Support Team Lead,2019-02-20,Full-Time,Remote,73962,EMP1000,Active
4,EMP1005,Mia,Sutton,Female,1970-02-22,mia.sutton@company.com,+1-232-576-4835,Sales,Account Manager,2023-07-26,Full-Time,Remote,91218,EMP1000,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,EMP1096,David,Sandoval,Male,1971-05-04,david.sandoval@company.com,001-252-605-8527x72217,Sales,Sales Manager,2023-02-21,Full-Time,Chennai,87577,EMP1023,Active
96,EMP1097,Dakota,Moody,Male,2000-04-11,dakota.moody@company.com,386-787-4034x5054,Marketing,Marketing Specialist,2021-01-07,Full-Time,Chennai,50076,EMP1005,Active
97,EMP1098,Jeffrey,Ross,Male,1983-10-10,jeffrey.ross@company.com,627-775-8416x16928,Finance,Finance Manager,2026-02-16,Full-Time,Chennai,96495,EMP1081,Active
98,EMP1099,Brian,Murphy,Male,1978-06-10,brian.murphy@company.com,001-362-875-7059x640,Customer Support,Support Executive,2022-01-21,Full-Time,Chennai,52685,EMP1019,Active
99,EMP1100,Jack,Owen,Male,1992-08-22,jack.owen@company.com,(897)202-1355,Engineering,Senior Software Engineer,2026-02-05,Full-Time,Remote,73963,EMP1057,Active

Write an SQL query to display employees whose salary is greater than 50000.

In [7]:
employees_high_salary = df[df['Salary'] > 50000]
display(employees_high_salary)

,EmployeeID,FirstName,LastName,Gender,DateOfBirth,Email,PhoneNumber,Department,JobTitle,HireDate,EmploymentType,Location,Salary,ManagerID,Status
0,EMP1001,Mark,Johnson,Male,1977-09-05,mark.johnson@company.com,001-218-519-6001x3389,Engineering,Engineering Manager,2020-04-12,Full-Time,Chennai,74481,EMP1000,Terminated
3,EMP1004,Angel,Perez,Male,1978-03-18,angel.perez@company.com,516.647.5255,Customer Support,Support Team Lead,2019-02-20,Full-Time,Remote,73962,EMP1000,Active
4,EMP1005,Mia,Sutton,Female,1970-02-22,mia.sutton@company.com,+1-232-576-4835,Sales,Account Manager,2023-07-26,Full-Time,Remote,91218,EMP1000,Active
5,EMP1006,Rodney,Trujillo,Male,1982-05-06,rodney.trujillo@company.com,001-553-676-7242,Customer Support,Support Executive,2019-01-11,Full-Time,Remote,53490,EMP1000,Active
6,EMP1007,Paul,Patterson,Male,1989-02-03,paul.patterson@company.com,(387)810-1226,Sales,Sales Executive,2021-05-22,Full-Time,Remote,56534,EMP1000,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,EMP1096,David,Sandoval,Male,1971-05-04,david.sandoval@company.com,001-252-605-8527x72217,Sales,Sales Manager,2023-02-21,Full-Time,Chennai,87577,EMP1023,Active
96,EMP1097,Dakota,Moody,Male,2000-04-11,dakota.moody@company.com,386-787-4034x5054,Marketing,Marketing Specialist,2021-01-07,Full-Time,Chennai,50076,EMP1005,Active
97,EMP1098,Jeffrey,Ross,Male,1983-10-10,jeffrey.ross@company.com,627-775-8416x16928,Finance,Finance Manager,2026-02-16,Full-Time,Chennai,96495,EMP1081,Active
98,EMP1099,Brian,Murphy,Male,1978-06-10,brian.murphy@company.com,001-362-875-7059x640,Customer Support,Support Executive,2022-01-21,Full-Time,Chennai,52685,EMP1019,Active
99,EMP1100,Jack,Owen,Male,1992-08-22,jack.owen@company.com,(897)202-1355,Engineering,Senior Software Engineer,2026-02-05,Full-Time,Remote,73963,EMP1057,Active

Write an SQL query to display employees ordered by salary in descending order.

In [8]:
employees_sorted_by_salary = df.sort_values(by='Salary', ascending=False)
display(employees_sorted_by_salary)

,EmployeeID,FirstName,LastName,Gender,DateOfBirth,Email,PhoneNumber,Department,JobTitle,HireDate,EmploymentType,Location,Salary,ManagerID,Status
86,EMP1087,Katie,Smith,Female,1978-12-06,katie.smith@company.com,473-832-2141x88805,Operations,Operations Manager,2026-01-31,Full-Time,Bangalore,103186,EMP1040,Active
61,EMP1062,Mallory,Oliver,Female,1992-07-30,mallory.oliver@company.com,+1-421-504-7095x21456,Human Resources,HR Manager,2024-04-01,Full-Time,Mumbai,101580,EMP1030,Active
17,EMP1018,Jimmy,Murillo,Male,2004-05-11,jimmy.murillo@company.com,484.925.1354,Sales,Account Manager,2019-02-01,Full-Time,Pune,100560,EMP1017,Active
68,EMP1069,Victoria,Fernandez,Female,1997-01-17,victoria.fernandez@company.com,6202539502,Customer Support,Support Team Lead,2019-05-19,Contract,Hyderabad,100083,EMP1029,Active
72,EMP1073,Jennifer,Davis,Female,1983-04-17,jennifer.davis@company.com,(227)711-1161x528,Customer Support,Support Team Lead,2023-10-21,Full-Time,Remote,98520,EMP1070,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,EMP1082,Carrie,Hernandez,Female,1995-08-04,carrie.hernandez@company.com,001-977-699-7995x52717,Operations,Operations Executive,2019-02-07,Full-Time,Delhi,38123,EMP1073,Active
37,EMP1038,Kim,Stanley,Female,1970-01-19,kim.stanley@company.com,4676165726,Operations,Operations Executive,2023-08-31,Intern,Hyderabad,37059,EMP1005,Active
44,EMP1045,Justin,Butler,Male,1989-07-23,justin.butler@company.com,001-586-577-4964x99091,Customer Support,Support Executive,2023-06-07,Contract,Bangalore,36895,EMP1023,Active
71,EMP1072,Zachary,Schmidt,Male,1984-04-15,zachary.schmidt@company.com,918-836-7365,IT,System Administrator,2023-05-01,Full-Time,Delhi,36778,EMP1042,Active
1,EMP1002,Mike,Miles,Male,1983-01-09,mike.miles@company.com,302-765-4235x116,Customer Support,Support Executive,2022-01-31,Full-Time,Pune,34743,EMP1000,On Leave

Write an SQL query to find the maximum salary among all employees.

In [9]:
max_salary = df['Salary'].max()
print(f"The maximum salary among all employees is: {max_salary}")

The maximum salary among all employees is: 103186

Write an SQL query to find the minimum salary among all employees.

In [10]:
min_salary = df['Salary'].min()
print(f"The minimum salary among all employees is: {min_salary}")

The minimum salary among all employees is: 34743

Write an SQL query to calculate the average salary of employees.

In [11]:
average_salary = df['Salary'].mean()
print(f"The average salary of employees is: {average_salary:.2f}")

The average salary of employees is: 60712.65

Write an SQL query to count the total number of employees.

In [12]:
total_employees = len(df)
print(f"The total number of employees is: {total_employees}")

The total number of employees is: 100

Write an SQL query to count employees in each department.

In [13]:
employees_by_department = df.groupby('Department').size().sort_values(ascending=False)
print("Number of employees in each department:")
display(employees_by_department)

Number of employees in each department:

Department
Customer Support    17
Finance             17
Sales               14
Human Resources     13
Operations          13
Engineering          9
IT                   9
Marketing            8
dtype: int64

Write an SQL query to display employee names along with their department manager names using INNER JOIN.

In [14]:
# Create a copy of the DataFrame to represent managers
managers_df = df[['EmployeeID', 'FirstName', 'LastName']].copy()
managers_df.rename(columns={'EmployeeID': 'ManagerEmployeeID', 'FirstName': 'ManagerFirstName', 'LastName': 'ManagerLastName'}, inplace=True)

# Merge the original DataFrame with the managers_df
employees_with_managers = pd.merge(
    df[['EmployeeID', 'FirstName', 'LastName', 'ManagerID']],
    managers_df,
    left_on='ManagerID',
    right_on='ManagerEmployeeID',
    how='inner'
)

# Select and display the required columns
display(employees_with_managers[['FirstName', 'LastName', 'ManagerFirstName', 'ManagerLastName']])

   FirstName   LastName ManagerFirstName ManagerLastName
0     Joseph     Obrien              Mia          Sutton
1       Adam  Zimmerman            James         Ferrell
2      David    Kennedy             Kyle           Burns
3     Brenda      White             Mike           Miles
4       John      Lewis          Tiffany             Liu
..       ...        ...              ...             ...
85     David   Sandoval          Richard       Rodriguez
86    Dakota      Moody              Mia          Sutton
87   Jeffrey       Ross            Kelly          Foster
88     Brian     Murphy              Roy          Warner
89      Jack       Owen          Richard           Baker

[90 rows x 4 columns]

Write an SQL query to display all employees and their department details using LEFT JOIN.

In [15]:
department_details_df = employees_by_department.reset_index()
department_details_df.columns = ['Department', 'EmployeeCountInDepartment']

employees_with_department_details = pd.merge(
    df,
    department_details_df,
    on='Department',
    how='left'
)

print("Employees with Department Details (including employee count per department):")
display(employees_with_department_details[['EmployeeID', 'FirstName', 'LastName', 'Department', 'EmployeeCountInDepartment']])

Employees with Department Details (including employee count per department):

   EmployeeID FirstName  LastName        Department  EmployeeCountInDepartment
0     EMP1001      Mark   Johnson       Engineering                          9
1     EMP1002      Mike     Miles  Customer Support                         17
2     EMP1003      Ryan     Munoz   Human Resources                         13
3     EMP1004     Angel     Perez  Customer Support                         17
4     EMP1005       Mia    Sutton             Sales                         14
..        ...       ...       ...               ...                        ...
95    EMP1096     David  Sandoval             Sales                         14
96    EMP1097    Dakota     Moody         Marketing                          8
97    EMP1098   Jeffrey      Ross           Finance                         17
98    EMP1099     Brian    Murphy  Customer Support                         17
99    EMP1100      Jack      Owen       Engineering                          9

[100 rows x 5 columns]

Write an SQL query to display employees whose salary is above the average salary.

In [16]:
employees_above_average_salary = df[df['Salary'] > average_salary]
print(f"Employees with salaries above the average salary ({average_salary:.2f}):")
display(employees_above_average_salary[['EmployeeID', 'FirstName', 'LastName', 'Salary']])

Employees with salaries above the average salary (60712.65):

   EmployeeID FirstName   LastName  Salary
0     EMP1001      Mark    Johnson   74481
3     EMP1004     Angel      Perez   73962
4     EMP1005       Mia     Sutton   91218
13    EMP1014    Brenda      White   73892
14    EMP1015      John      Lewis   82776
17    EMP1018     Jimmy    Murillo  100560
18    EMP1019       Roy     Warner   65276
19    EMP1020  Mitchell     Harris   60964
22    EMP1023   Richard  Rodriguez   71348
26    EMP1027  Jennifer    Bentley   89181
29    EMP1030    Justin     Lowery   64644
31    EMP1032     Janet  Hernandez   61809
40    EMP1041   Michael     Brewer   81110
46    EMP1047   Michael     Gibson   77514
49    EMP1050      Mark    Vasquez   75738
51    EMP1052     Peter     Harris   95724
53    EMP1054     James      Weeks   76215
55    EMP1056  Kathleen    Johnson   93258
56    EMP1057   Richard      Baker   85409
58    EMP1059    Joseph     Knight   74267
59    EMP1060       Joe    Estrada   68492
61    EMP1062   Mallory     Oliver  101580
63    EMP1064    Rachel      Smith   61256
65    EMP1066    Meagan       Paul   79472
67    EMP1068  Virginia   Buchanan   87701
68    EMP1069  Victoria  Fernandez  100083
69    EMP1070      Beth     Fisher   74446
72    EMP1073  Jennifer      Davis   98520
77    EMP1078    Donald    Fischer   78186
79    EMP1080     Scott   Johnston   78630
83    EMP1084    Joanna    Pacheco   91139
84    EMP1085      Jack     Hardin   89723
85    EMP1086    Thomas    Collins   84179
86    EMP1087     Katie      Smith  103186
89    EMP1090      Ruth      Solis   78117
95    EMP1096     David   Sandoval   87577
97    EMP1098   Jeffrey       Ross   96495
99    EMP1100      Jack       Owen   73963

Write an SQL query to find departments that have employees.

In [17]:
departments_with_employees = df['Department'].unique()
print("Departments that have employees:")
for department in departments_with_employees:
    print(f"- {department}")

Departments that have employees:
- Engineering
- Customer Support
- Human Resources
- Sales
- Operations
- Marketing
- Finance
- IT